logic/menu_logic.go, service/isql/menu_isql.go
=> 修复登录后未能按照用户实际菜单权限加载菜单的

logic/menu_logic.go, service/isql/menu_isql.go, service/isql/user_isql.go
=> fix修改用户信息后，用户无法登录的bug

service/ildap/user_ildap.go
**填写PR内容：**
- 啊哈，还是踩了地址传递修改值的坑
=> fix: ldap password 因为地址传递而变化导致无法登陆

service/isql/operation_log_isql.go
- [✅] 我已阅读并理解[贡献者指南]()。
- [✅] 我已检查没有与此请求重复的拉取请求。
- [✅] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [✅] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
**填写PR内容：**
fix：日志延迟+日志丢失问题
-
-
-
=> fix: 日志延迟+丢失问题

service/isql/operation_log_isql.go
- [✅] 我已阅读并理解[贡献者指南]()。
- [✅] 我已检查没有与此请求重复的拉取请求。
- [✅] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [✅] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
**填写PR内容：**
- 日志切片为空逻辑优化
=> 日志切片为空逻辑优化

logic/a_logic.go, logic/dingtalk_logic.go
**填写PR内容：**
fix: dingding多级部门同步
- 钉钉多级部门同步的问题 #71
=> fix: dingding多级部门同步

model/user.go, public/client/feishu/feishu.go
=> fix: 飞书手机号超过11位的问题

public/client/feishu/feishu.go
**填写PR内容：**
- fix: 修复飞书根部门用户获取问题
=> fix: 修复飞书根部门用户获取问题

logic/user_logic.go
**填写PR内容：**
- 添加和更新用户时关于用户角色校验的问题
=> fix: 用户操作过程中角色权限的一些校验问题

config.yml, config/config.go, public/client/openldap/openldap.go, public/common/ldap.go, service/ildap/group_ildap.go, service/ildap/user_ildap.go
**填写PR内容：**
feat: LDAP 添加连接池支持
=> feat: LDAP 添加连接池支持

.github/FUNDING.yml, logic/dingtalk_logic.go, logic/feishu_logic.go, logic/wecom_logic.go
**填写PR内容：**
- 添加赞助页,以及暴漏添加部门用户失败的名字
-
-
=> 🎡 feat: 添加赞助页,以及暴漏添加部门用户失败的名字

README.md
**填写PR内容：**
- ⚗️ readme添加徽标
-
-
=> ⚗️ readme添加徽标

logic/a_logic.go, public/client/wechat/wecom.go
**填写PR内容：**
- 企业微信同步用户之后部门获取的问题
- 兼容手机号为空时用户添加失败的问题
=> ☄️ fix: 企业微信同步用户之后部门的问题,兼容用户没有手机号同步失败的问题

public/tools/type.go
=> ☄️ feat: 增强名字转为拼音的兼容性

public/tools/type.go
=> 🐡 feat: 处理拼音转换的问题

README.md
=> 🐲 add friend links

logic/user_logic.go
=> fix: 修复添加用户时的分组问题

docs/sql/go_ldap_admin.sql
=> fix: sql sync

controller/a_controller.go, public/common/validator.go
=> fix 调整手机号校验的规则

public/common/database.go
=> fix: 添加字段关系表的初始化

docs/docker-compose/config/init.ldif
=> fix: feishu root typo

controller/group_controller.go, controller/user_controller.go, logic/a_logic.go, logic/sqlToLdap_login.go, model/group.go, model/request/group_req.go, model/request/user_req.go, model/user.go, public/common/init_mysql_data.go, routes/group_routes.go, routes/user_routes.go, service/ildap/group_ildap.go, service/ildap/user_ildap.go, service/isql/group_isql.go, service/isql/user_isql.go
**填写PR内容：**
- 添加数据库未能成功与ldap对齐的数据补偿能力。
=> feat: 添加sql数据补偿能力

docs/docker-compose/docker-compose.yaml
=> 更换docker image代理,解决镜像不更新的问题

public/common/database.go
=> fix: sqlite3 并发之后被 lock 的问题

controller/base_controller.go, logic/base_logic.go, model/request/base_req.go, public/common/ldap.go, public/tools/email.go, routes/base_routes.go
重置密码添加验证码的校验，解决被恶意重置的问题。 感谢 [@Sunshine-JamesHu](https://github.com/Sunshine-JamesHu) 提供的思路建议。
=> feat: 优化重置密码的逻辑,添加验证码校验

.github/workflows/go-binary-release.yml
- 添加后端自动构建二进制的能力，以解决二进制历史版本存留的问题。
=> feat: 添加二进制构建的 action

.pre-commit-config.yaml, README.md, public/tools/ssha.go, public/tools/util_test.go, service/ildap/user_ildap.go
=> feat: 平台中创建的用户密码默认使用ssha加密策略

public/client/feishu/feishu.go
**填写PR内容：**
- fix #238 中提到的同步飞书用户时pageToken没有重置的问题
=> fix: 修复同步飞书用户时pageToken没有重置的问题

config.yml, config/config.go, go.mod, go.sum, logic/dingtalk_logic.go, public/client/dingtalk/dingtalk.go
- [*] 我已阅读并理解[贡献者指南](https://github.com/eryajf/go-ldap-admin/blob/main/CONTRIBUTING.md)。
- [*] 我已检查没有与此请求重复的拉取请求。
- [*] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [*] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
**填写 PR 内容：**
- dintablk包2.1.0 更新了部分结构字段
- 添加按时间范围查询离职员工接口
- 本地测试正常：
-
=> dingtalk2.1.0版本包添加按日期范围查询离职员工接口及

logic/dingtalk_logic.go, logic/feishu_logic.go, logic/wecom_logic.go
=> fix: 修复同步用户时处理离职用户的异常

public/common/init_mysql_data.go
=> fix: 管理员初始化时默认邮箱的问题

logic/feishu_logic.go
=> fix: 飞书处理离职用户是字段错误的问题

logic/user_logic.go
=> fix: 用户更新时提交默认分组的问题

logic/user_logic.go
**填写 PR 内容：**
- 修复更新用户时的逻辑bug。
close #278 #281
=> fix: 修复更新用户的逻辑bug

config.yml, config/config.go, docs/docker-compose/config/init.ldif, model/request/menu_req.go, public/common/init_mysql_data.go, service/ildap/user_ildap.go
**填写 PR 内容：**
- 修复parentid为0值的问题
- 补充启动时的初始化数据  close #306  close #291 
- 用户密码加密类型可配置化 close #285
=> feat: 修复parentid为0值的问题;补充启动时的初始化数据;用户密码加密类型可配置化

README.md
=> doc: readme新增友链项目

service/ildap/user_ildap.go
=> fix: 当用户策略为clear时,存入原文

service/isql/operation_log_isql.go
=> fix: 修复sqlite无法执行truncate的问题
